### ISSUE TITLE
!!play is bugged

### ISSUE THREAD

**Issue by ctnkaan** [ctnkaan/Noodle#7]

**Comment by ctnkaan** [comment]
`TypeError: input stream: Cannot read property 'headers' of undefined
    at exports.getBasicInfo (E:\Programming\Source Codes\Discord Development\noodle\node_modules\ytdl-core\lib\info.js:51:31)     
    at E:\Programming\Source Codes\Discord Development\noodle\node_modules\ytdl-core\lib\info.js:472:46
    at Map.getOrSet (E:\Programming\Source Codes\Discord Development\noodle\node_modules\ytdl-core\lib\cache.js:29:19)
    at Object.exports.<computed> [as getBasicInfo] (E:\Programming\Source Codes\Discord Development\noodle\node_modules\ytdl-core\lib\info.js:472:26)    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getInfo (E:\Programming\Source Codes\Discord Development\noodle\node_modules\ytdl-core\lib\info.js:362:14)       at async E:\Programming\Source Codes\Discord Development\noodle\node_modules\ytdl-core\lib\cache.js:33:11`

**Comment by ctnkaan** [comment]
Will write a new play function. Could use a different library
